### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by kpodemski** [Oksydan/falconize#1]
This is another project you've created that use a GPL license, which I see as problematic since if I use your product in my module, I have to release the rest of the code under the same license. Could you consider changing it?

**Comment by kpodemski** [comment]
More on the subject: https://codecalamity.com/the-gpl-is-evil/

**Comment by Oksydan** [comment]
Hi @kpodemski 

Good point 😉 . Yes, I will change the license.

**Comment by Oksydan** [comment]
Hi @kpodemski,

new version has been released with MIT license.
I am closing this issue. Thank you for your suggestion 😉

**Comment by kpodemski** [comment]
Thanks, suggestion is also valid for other products. I know people probably don't care but it's the same situation with cresting themes on Falcon, etc.

**Comment by Oksydan** [comment]
Yes, I am aware of that. I will change the Falcon 4 license, but I'm not sure what direction this project will go. I am currently even considering a paid license.
